# Generated by Django 4.2.2 on 2023-08-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_aseguradoras_coberturas_productores_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asegurados',
        ),
    ]
